# Basic Site Settings

include:
  - index.md

locale: "en-US"
site_theme: "default"
title: "Yan Jin"
title_separator: "-"
name: "Yan Jin"

description: "Biostatistics MS | Genomics & Functional Genomics | Single-cell & Spatial Transcriptomics"
url: "https://yan66627.github.io"
baseurl: ""
repository: "yan66627/yan66627.github.io"

# Sidebar Author Profile
author:
  avatar: "profile.png"
  name: "Yan Jin"
  pronouns: "he/him"
  bio: "MS in Biostatistics at Washington University in St. Louis. Research in aging genomics, spatial transcriptomics, epigenomics & regulatory genomics."
  location: "St. Louis, MO"
  employer: "Washington University in St. Louis"
  uri:
  email: "yjin66627@gmail.com"

  # Academic Profiles
  googlescholar: ""   # 如果你之后有 Google Scholar 链接可以填
  orcid: ""           # 可选
  pubmed: ""          # 目前你没有 PubMed 第一作者文章，可以留空
  ssrn:
  zotero:

  # Code & professional profiles
  github: "yan66627"
  linkedin: "http://linkedin.com/in/yan-jin-080246236"        # 若你有 LinkedIn，可以填这里

  # Social (可以留空)
  bluesky:
  twitter:
  instagram:
  mastodon:
